# -*- coding: utf-8 -*-
"""MOR_Model_Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ETLuFeX8izgPr_JlUy2Ahrkv0de4abTy
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

Y = pd.read_csv('MOR.csv')
X = np.load('MOR.npy')

X_train = X[:int(0.9*len(X))]
X_test = X[int(0.9*len(X)):]
y_train = Y[:int(0.9*len(Y))]
y_test = Y[int(0.9*len(Y)):]

y_train = y_train.values.ravel()
y_test = y_test.values.ravel()

model = RandomForestRegressor(
    n_estimators=200,
    max_depth=30,
    min_samples_split=2,
    max_features=0.8,
    bootstrap=True,
    random_state=42
)

model.fit(X_train, y_train)

# Evaluate the model on the test set
y_pred = model.predict(X_test)

# Calculate evaluation metrics
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

from joblib import dump

dump(model, 'HPT_CV.joblib')